### ISSUE TITLE
Archiving for Generic iOS Device gives error

### ISSUE THREAD

**Issue by ozgurshn** [kieranb662/CGExtender#1]
Thanks for ColorKitExamples, great library!
I got this error while archiving.
The files that have errors are CGExtender's CGPoint and CGSize.
It says use of undeclared type VectorArithmetic. How can I solve this problem?
You can replicate this issue by archiving your ColotKitExamples project.
![image](https://user-images.githubusercontent.com/2404074/86252821-5acf4400-bbbc-11ea-98bf-bd040b3804fe.png)

**Comment by kieranb662** [comment]
Hey Ozgur! 

Thanks for reaching out, this has been a recurring theme in archive builds. I can’t explain why it happens but  I think it is an Apple bug. One solution is to not use swift package manager when building. Instead directly drag and drop the files from the libraries into your app. I’m really sorry about that, it is an annoying process. 

Best wishes,
Kieran Brown

**Comment by ozgurshn** [comment]
hi Kiearan, thanks for getting back quickly. I ended up adding files to my project. That solved the problem.

**Comment by ozgurshn** [comment]
ColorKit RGB picker will be in use with the new version of my App Icon Maker app. https://apps.apple.com/tr/app/mobile-app-icon-maker-designer/id1521215185

**Comment by kieranb662** [comment]
Nice!!!
